# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: Daniel Schorin
email: djschor@umich.edu
description: >- # this means to ignore newlines until "baseurl:"
  Personal Website for Daniel Schorin
baseurl:  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: danielschorin
github_username:  djschor

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
permalink: slug
collections:
  apps:
    output: true
    permalink: /:title
    include: app-assets
defaults:
  - scope:
      path: ''
      type: 'apps'
    values:
      layout: 'app'
      type: 'app'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - gemfile
  - Gemfile.lock
  - license
  - CNAME
  - .babelrc
  - .npmignore
strict_front_matter: true
